INSERT INTO departments (department_name)
VALUES 
    ("Information Technology"),
    ("Administration"),
    ("Custodial"),
    ("Executive"),
    ("Circulation"),
    ("Reference Services"),
    ("Fiction Services"),
    ("Children's Services"),
    ("Young Adult Services");

INSERT INTO roles (title, salary)
VALUES 
    ("IT Specialist", 75000),
    ("Administrator", 35000),
    ("Custodian", 30000),
    ("Manager", 125000),
    ("Librarian", 50000),
    ("Library Assistant", 35000),
    ("Page", 16000);

INSERT INTO DepartmentRoles VALUES
    (1, 1),
    (1, 4), 
    (2, 2),
    (2, 4), 
    (3, 3),
    (3, 4), 
    (4, 4),
    (5, 4), 
    (5, 6),
    (5, 7),
    (6, 4), 
    (6, 5), 
    (6, 7),
    (7, 4),
    (7, 6),
    (7, 7),
    (8, 4),
    (8, 5),
    (8, 6),
    (8, 7),
    (9, 4),
    (9, 5),
    (9, 6),
    (9, 7);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
    ("Opal","Mcdonald",1,121),
    ("Madison","Spencer",1,121),
    ("Sanaa","Munoz",1,121),
    ("Hajra","Cordova",1,121),
    ("Kajus","Terry",1,121),
    ("Crystal","Ho",2,117),
    ("Annabel","Schroeder",2,117),
    ("Arun","Lin",2,117),
    ("Ishaq","Morales",2,117),
    ("Siena","Payne",2,117),
    ("Hafsa","Arnold",2,117),
    ("Jacques","Casey",3,125),
    ("Mabel","Combs",3,125),
    ("Fletcher","Mathews",3,125),
    ("Amna","Hampton",3,125),
    ("Anaya","Blake",4,118),
    ("Michelle","Bonilla",4,118), // Human Resources Manager
    ("Lacey","Richards",4,118), // CEO
    ("Archibald","Fitzpatrick",4,118),
    ("Ameer","Hunt",4,118),
    ("Rohan","Navarro",2,118), // IT Director
    ("Rafael","Santana",4,118),
    ("Brooklyn","Nixon",4,118),
    ("Joe","Hammond",4,118),
    ("Glenn","Henderson",4,118), // Building operations
    ("Riya","Small",5,133), // REF
    ("Rhianna","Slater",5,133), // REF
    ("Zuzanna","Bradford",5,133), // REF
    ("Malaika","Dunlap",5,133), // ILL
    ("Yuvraj","Winters",5,133), // CHILD
    ("Oisin","Schultz",5,133), // FIC
    ("Georgia","Elliott",5,133), // CHILD
    ("Maeve","Cline",5,118), // Head Librarian
    ("Chanel","Love",5,133), // YA
    ("Pearl","Lucas",5,133), // FIC
    ("Damien","Aguirre",6,134),
    ("Mehmet","Rodgers",6),
    ("Tristan","Mack",6),
    ("Thalia","Hood",6,130),
    ("Myla","Pratt",6,130),
    ("Shauna","Winter",6,134),
    ("Floyd","Landry",6),
    ("Lilli","Gibbs",6,134),
    ("Phyllis","Stephens",6,130),
    ("Abdul","Charles",6),
    ("Juanita","Case",6),
    ("Kimberley","Meza",6),
    ("Gladys","Boyle",6),
    ("Ismaeel","O'Reilly",6),
    ("Abdirahman","Kennedy",6),
    ("Amelia","Mcintyre",6,130),
    ("Emre","Torres",6),
    ("Zaynab","Odonnell",6),
    ("Ezekiel","Bolton",6),
    ("Conor","Rocha",6),
    ("Polly","Simpson",6),
    ("Haider","Duke",6),
    ("Ellie-May","George",6),
    ("Noel","Mcclure",6),
    ("Eugene","Rollins",6),
    ("Safia","Erickson",7), // 132 for children
    ("Rabia","Welsh",7),
    ("Ela","Johns",7),
    ("Tomos","Allen",7),
    ("Jayson","Alvarado",7),
    ("Steven","Mckee",7),
    ("Aleena","Abbott",7),
    ("Karina","Salas",7),
    ("Luke","Duran",7),
    ("Richie","Moore",7),
    ("Mckenzie","Lindsay",7),
    ("Leonie","Andersen",7),
    ("Ffion","Villarreal",7),
    ("Maison","Shepard",7),
    ("Jasmin","Spence",7),
    ("Carolyn","Cannon",7),
    ("Vinnie","Jacobs",7),
    ("Luc","Pham",7),
    ("Zahraa","Mccann",7),
    ("Isabel","Nichols",7),
    ("Guy","Kerr",7),
    ("Elysia","Thomas",7),
    ("Lochlan","Carr",7),
    ("Abdullah","Ramos",7),
    ("Ayah","Clay",7),
    ("Tianna","Griffith",7),
    ("Wyatt","Page",7),
    ("Ruby","Cuevas",7),
    ("Amir","Juarez",7),
    ("Kabir","Buchanan",7),
    ("Harmony","Goodwin",7),
    ("Woody","Hanna",7),
    ("Mario","Alexander",7),
    ("Robbie","Brady",7),
    ("William","Mason",7),
    ("Ciaran","Grimes",7),
    ("Jermaine","Guzman",7),
    ("Keaton","Cohen",7),
    ("Aysha","Mayer",7),
    ("Marcus","Logan",7);